### ISSUE TITLE
Gives a "Parser errors" when using a few Scenario Outlines in one feature file 

### ISSUE THREAD

**Issue by ikozakov** [smoll/greens#34]
I'm getting this error when running `greener`.
```
gems/gherkin3-pre-alpha-3.0.0.alpha.1/lib/gherkin3/parser.rb:81:in `parse': Parser errors:
(64:5): expected: #TagLine, #ExamplesLine, #Comment, #Empty, got 'Given I '
```
Cucumber runs that feature without any errors.

I this the issue is related to 
dependency on an old `gherkin` gem
```
gherkin3-pre-alpha ~> 3.0.0.alpha.
```

Can you (i can create a PR) update the gem with a new gherkin?

**Comment by ikozakov** [comment]
Oh I see it already has been updated
`spec.add_dependency "gherkin3", "~> 3.1.1"`
can you release a new version of greener? :)

**Comment by smoll** [comment]
Fixed in https://github.com/smoll/greener/commit/2426f492aca6dad4cd748f1087eba68209ca30cb
